-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1rT4sXr9QWlYkoX8JmTQYbNMyIPYoq2qbJ00gLowceSgCgYIKoZIzj0DAQehRANCAAS4IGEDQpQaxLlfUqbBSdzbYn2JToKfikOg4+zU+EjVHzIuc7bNeeKgB+g34uZCPYImw+kmnq5vp+TLiIE2YvH2
-----END PRIVATE KEY-----